### PR TITLE
export a blobToArrayBuffer function

### PR DESCRIPTION
**Pull request by trevj**
Add a function which will convert a Blob to an ArrayBuffer, working around the following issue specific to Firefox add-ons:
https://bugzilla.mozilla.org/show_bug.cgi?id=1122687

### CODE REVIEW

**Comment by willscott** [comment]
@bemasc - Thoughts on whether we can reasonably make this a transparent part of the adapter, versus whether the client needs to explicitly call the conversion function as in this design?

**Comment by bemasc** [comment]
Unclear.  It depends on what you mean by "reasonable", and also on some weird details about what browsers actually implement, which I don't know.

In a mutation style, it would be like
```javascript
var fixDataChannel = function(dc) {
  var provideMessage;
  var gotMessage = function(event) {
    if (!provideMessage) {
     return;
    }
    if (event.data instanceof Blob && dc.binaryType == 'arraybuffer') {
      event.data = blobToArrayBuffer(msg.data);
    }
    provideMessage(event);
  };
  dc.onmessage = gotMessage;
  Object.defineProperty(dc, 'onmessage', {
    set: function(x) { provideMessage = x; },
    get: function() { return provideMessage; }
  });
}

var provideDataChannel;
var gotDataChannel = function(dc) {
  if (provideDataChannel) {
    fixDataChannel(dc);
    provideDataChannel(dc);
  }
};
pc.ondatachannel = gotDataChannel;
Object.defineProperty(pc, 'ondatachannel', {
  set: function(x) { provideDataChannel = x; },
  get: function() { return provideDataChannel; }
});
```

If that works then "great" ... otherwise we would have to implement complete surrogate RTCPeerConnection and RTCDataChannel classes and pass every method call and attribute set through, with appropriate modifications.

**Comment by bemasc** [comment]
Oh, and we should check whether any of the browsers have real events on RTCPeerConnection or RTCDataChannel yet.  The W3C spec mentions some...

If there are events then that would make this a lot easier ... depending on how those events interact with the `.ondatachannel` and `.onmessage` handlers work.  If those handlers run first, then we still have to do this.  If they run "downstream", then we could just eat the events and re-fire them with the relevant changes.  Anyway, some experimentation would be required.

**Comment by trevj** [comment]
I want to propose a second solution in which we add a `blob` field to `core.rtcdatachannel`'s `onmessage` event.

Reading the spec just now, I see that `Blob` is actually defined in the spec as the default `binaryType` for datachannels!:
http://w3c.github.io/webrtc-pc/#widl-RTCDataChannel-binaryType

Was there a reason we omitted blobs when designing the interface?

The downside, obviously, is that Firefox add-on users would be "stuck" converting blobs; however, it's not clear to me that we need or can to workaround every browser bug (@bemasc's comment above sounds like a daunting-albeit-moderately-interesting engineering exercise).

**Comment by bemasc** [comment]
If freedom can pass Blobs across the interface, then I agree with trevj@'s assessment.  However, that doesn't conflict with my feeling that the design implemented here --- exposing a helper function in the adapter and using it to perform the fixup in core.rtcpeerconnection --- seems reasonable enough.

**Comment by willscott** [comment]
I like @bemasc's mutation style fixup because it means there's no way for other clients to get tripped up by this bug. Can we test if that works in firefox addons? if it does, awesome! If it doesn't, the current design is reasonable and the best alternative we've got.

**Comment by trevj** [comment]
It's worth a try. I hacked a simple script which establishes a peerconnection and tries to send 'hello world!' across a datachannel.

I don't think mutations will work for us. In Firefox, at least, while the `set` function is invoked, `get` never is:

```js
answerer.ondatachannel = function(event) {
  var channel = event.channel;

  var handler;
  Object.defineProperty(channel, 'onmessage', {
    set: function(x) {
      handler = x;
    },
    get: function() {
      return handler;
    }
  });

  channel.onmessage = function(e) {
      console.info('received message!');
  };
};
```

As for intercepting events, `DataChannel` doesn't seem to truly implement `EventListener`. While `onmessage` is invoked as expected, my event listener never is (again, in Firefox):

```js
answerer.ondatachannel = function(event) {
  console.info('i can see a new datachannel');
  var channel = event.channel;

  channel.addEventListener('onmessage', function(e) {
    console.info('i see an event!');
  }, true);

  channel.onmessage = function(e) {
      console.info('received message!');
  };
};
```

**Comment by willscott** [comment]
I patched @bemasc's sample in, and it seems to work!  'get' isn't getting
called because the user isn't looking at the property. That's okay though.
When onmessage gets run by the system, what runs is the interposed handle
that cleans the incoming event before sending it to the custom-set
user-defined handler.

In addition to what @bemasc pasted, we'll need to interpose on
createDataChannel and fix up that method of getting a dataChannel as well.

The other thing I'm seeing is that the dc's binaryType is 'blob'. should
core.rtcDataChannel always be setting binaryType to arraybuffer at
construction time?

**Comment by bemasc** [comment]
Wow, I'm actually shocked that this works.  OK.

I just checked, and actually the EventTarget interface for RTCPeerConnection _is_ implemented, in Firefox and Chrome.  Unfortunately, that means that the Object.defineProperty trick only fixes part of the interface (`pc.addEventListener('datachannel', ...)` will still get the buggy behavior in Firefox).

I'm OK with landing the `Object.defineProperty` monkeypatch in our adapter, and leaving the EventTarget interface unfixed, but we should definitely check that it actually makes uProxy work.

I do think that we shouldn't spend too much time on this.  It sure seems like we're the only ones who are trying to send ArrayBuffers through DataChannels in a Firefox Add-On, so the only benefit here is a bit of abstract architectural purity, which we'd be paying for in code wackiness.

**Comment by willscott** [comment]
on my firefox when testing in the addon at least  'addEventListener' is not
defined on the data channel :)

**Comment by willscott** [comment]
Also, in the addon context in firefox you do get access to es6 'new
Proxy()', which is an even more powerful way to interpose on needed events,
so i guess that could be an approach as well.

**Comment by bemasc** [comment]
Interesting.  I only checked in the Firefox webpage environment, on RTCPeerConnection itself.

**Comment by willscott** [comment]
Having done all that, I'm now not convinced there's a bug here.

I added
```javascript
bobchannel.setBinaryType('arraybuffer');
```
and
```javascript
aliceChannel.setBinaryType('arraybuffer')
```

and Firefox gave me an arraybuffer as desired. So it sounds like the only difference is that firefox is defaulting to blobs, but if asked explicitly to give an arrayBuffer, it will.

**Comment by trevj** [comment]
Yes, Firefox defaults to blobs but did you try this in a Firefox add-on?

**Comment by willscott** [comment]
Yep - I added those two lines to the freedom-for-firefox integration tests,
and was running it in the addon JSM context.

**Comment by trevj** [comment]
I can't explain that. I did (I think) the exact same thing and it doesn't work on my system, even with Firefox 36. Can you attach a copy of the zip?

**Comment by willscott** [comment]
http://www.filedropper.com/testaddon

**Comment by trevj** [comment]
Good catch! There's a lot of stuff to wade through in that zip!

However, building on the recent comments to my [FileReader.readAsArrayBuffer issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1122687) but I was able to get my own test case working by:
 1. importing `ArrayBuffer`, in addition to `Blob`, from `Services.appShell.hiddenDOMWindow`
 1. setting `binaryType = 'arraybuffer'` on (just) the answerer side (Bob in your example, I think)

Will, do you think your demo is also pulling in ArrayBuffer in a similar way? Regardless of the answer, I think I can now assemble a much simpler fix for Freedom.

**Comment by willscott** [comment]
Yep, just the full freedom-for-firefox integration test bundle. The one file to look at is the rtcpeerconnection.src.js integration test file, which has some additional console logging, and two lines added to explicitly set binaryType.

I think ArrayBuffer is already pulled in by freedom-for-firefox, maybe? I didn't have to do anything with that to get this to work.

**Comment by trevj** [comment]
So, I just tried `cfx run`-ing your attached add-on and I don't see `WHOOO!` with or without the calls to `setBinaryType`. I don't see any kind of consistent results from running freedom-for-firefox's `grunt test`.

I definitely *do* need to import `ArrayBuffer`, from `Services.appShell.hiddenDOMWindow`, otherwise I receive Blobs.

Problem is, when I hacked freedom-for-chrome to import `ArrayBuffer` as described above, it completely messes up my ability to use `ArrayBuffer` in the `SocksToRtc` module.

@willscott Does the discussion on this issue make any sense to you:
https://bugzilla.mozilla.org/show_bug.cgi?id=1122687

**Comment by willscott** [comment]
I think it's important to distinguish that the context of a JSM (where
webrtc-adapter is compiled to in the freedom-for-firefox.jsm) is yet again
different from the 'main.js' context of a normal addon.

So your example & pulling in of hiddenDOMWindow in main.js will behave
differently from when that's done in the JSM.

**Comment by trevj** [comment]
Good to know, though I suspect that isn't the case here because I'm seeing different behaviour in Simple SOCKS depending on whether I've hacked `freedom-for-firefox` to import `hiddenWindow.ArrayBuffer` or not.

The ultimate cause certainly *seems* to be how we are importing `ArrayBuffer` but I suspect the solution is not trivial and that our time is better spent unblocking Firefox proxying via the solution I originally presented -- we can refine as new information becomes available (probably via the Bugzilla issues I've filed).

Thoughts, @willscott, @bemasc, @iislucas?

**Comment by iislucas** [comment]
+1  I'd much rather minimize effort on elegant hacks that workaround a bugs that should be fixed in firefox, and put more time on having them fixed there and use a longer workaround in the meantime.

**Comment by bemasc** [comment]
I have lost track of this discussion, but I would at least like us to have consistent reproduction of the failing behavior before we attempt to implement a workaround.

**Comment by trevj** [comment]
@iislucas It's a little tricky because I suspect there is *some* path for `ArrayBuffer` use through the maze of twisty passages that is Firefox's add-on environment(s). Given that I have a workaround, however, I'd still prefer put the "elegant fix" on the backburner and forge ahead with what will surely be other Firefox tasks.

@bemasc Simple SOCKS is a good example of consistent failing behaviour :-) While the "elegant fix" works for me in a dirt-simple Firefox add-on (which I attached to [my Bugzilla issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1122682)), I *cannot* verify that it fixes, as @willscott states, freedom-for-firefox's integration tests. The "send string across a datachannel" test in that suite is basically junk for me in Firefox -- @willscott which version of Firefox and OS were you running against? Are you triply sure it returned an `ArrayBuffer`? Sure enough to run Simple SOCKS?

**Comment by trevj** [comment]
BTW, to be clear, the elegant and simpler "just set binaryType" fix *does not fix* Simple SOCKS on my system, regardless of the integration tests :-)

**Comment by willscott** [comment]
per previous question, I'm on Mac / Firefox 34. 

I have two thoughts on this area at this point:
1. I prefer @bemasc's mutation mechanism in webrtc-adapter, since it will mean that other client's can't run into the bug, and there are already other non-uproxy non-freedom code using this very general library per NPM.

2. We are in a very confusing state because none of us have been willing to fix the firefox webrtc tests. We really need to do that to understand the impact of bugs like this and where they do/don't reproduce. I went in last week and fiddled with them in https://github.com/freedomjs/freedom/pull/198 and it seems like there's tractable progress to be made.

**Comment by trevj** [comment]
OK. I've been using Linux / Firefox 35. Interesting that the tests run more reliably for you; I wonder what happens if you actually try to run Simple SOCKS with your fix?

 1. I prefer another solution too. How many of those users are running in Firefox add-ons? Is the adapter intended to work around browser incompabilities or bugs or both?
 1. Agreed.

I'm not saying we shouldn't do the elegant thing, BTW, but it's getting a little bit beyond my current Firefox skills.

BTW, what about my proposal to support for Blobs?

**Comment by trevj** [comment]
As discussed over email, the blob conversion function(s) are probably better placed in the `core.rtcdatachannel` provider:
https://github.com/freedomjs/freedom/pull/203

**Pull request closed without merging**
